## To see all available configs, please check the documentation
## https://github.com/TerraHubCorp/terrahub/tree/master/docs
## project config
project:
  name: 'kperrow/WordOps'
  code: 'c23aa3c2'
  include:
    - '.'
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'

## terraform config
terraform:
  varFile:
    - 'default.tfvars'
